import React from "react";

function PortfolioPDF({ githubData }) {
  if (!githubData) return null;

  return (
    <div style={page}>
      {/* ================= CONTENT ================= */}
      <div style={container}>
        {/* ================= HEADER ================= */}
        <div style={header}>
          <img src={githubData.avatar} alt="avatar" style={avatar} />

          <div>
            <h1 style={name}>{githubData.name}</h1>
            <p style={username}>@{githubData.username}</p>
            <p style={bio}>{githubData.bio || ""}</p>
          </div>
        </div>

        <hr style={hr} />

        {/* ================= STATS ================= */}
        <Section title="GITHUB OVERVIEW">
          <div style={statsRow}>
            <Box label="Repos" value={githubData.publicRepos || 0} />
            <Box label="Stars" value={githubData.stars || 0} />
            <Box label="Followers" value={githubData.followers || 0} />
          </div>
        </Section>

        {/* ================= TECH STACK ================= */}
        {githubData.languages?.length > 0 && (
          <Section title="TECH STACK">
            <div style={chips}>
              {githubData.languages.map((l) => (
                <span key={l} style={chip}>
                  {l}
                </span>
              ))}
            </div>
          </Section>
        )}

        {/* ================= PROJECTS ================= */}
        {/* ================= TOP PROJECTS ================= */}
        {githubData.repos?.length > 0 && (
          <Section title="LATEST PROJECTS">
            {[...githubData.repos]
              .sort((a, b) => new Date(b.updated_at) - new Date(a.updated_at))
              .slice(0, 6)
              .map((repo) => (
                <div key={repo.name} style={card}>
                  <div style={cardTop}>
                    <span>{repo.name}</span>
                    <span>⭐ {repo.stars || 0}</span>
                  </div>

                  <p style={desc}>
                    {repo.description || "No description available"}
                  </p>

                  <div
                    style={{
                      display: "flex",
                      justifyContent: "space-between",
                      marginTop: 5,
                      fontSize: 9,
                      color: "#666",
                    }}
                  >
                    <span>{repo.language || "Unknown"}</span>

                    <span>
                      Updated: {new Date(repo.updated_at).toLocaleDateString()}
                    </span>
                  </div>
                </div>
              ))}
          </Section>
        )}

        {/* ================= FOOTER ================= */}
        <div style={footer}>
          Generated by DevHub • {new Date().toLocaleDateString()}
        </div>
      </div>
    </div>
  );
}

/* ================= COMPONENTS ================= */

function Section({ title, children }) {
  return (
    <section style={{ marginBottom: "24px" }}>
      <h3 style={titleStyle}>{title}</h3>
      {children}
    </section>
  );
}

function Box({ label, value }) {
  return (
    <div style={box}>
      <div style={{ fontSize: 14, fontWeight: 700 }}>{value}</div>
      <div style={{ fontSize: 9, color: "#666" }}>{label}</div>
    </div>
  );
}

/* ================= STYLES ================= */

const page = {
  width: "794px",
  height: "1123px",
  background: "#fff",
  color: "#111",
  fontFamily: "Arial",
};

const container = {
  padding: "32px",
};

const header = {
  display: "flex",
  gap: 16,
  alignItems: "center",
};

const avatar = {
  width: 78,
  height: 78,
  borderRadius: "50%",
  objectFit: "cover",
};

const name = {
  fontSize: 20,
  margin: 0,
};

const username = {
  fontSize: 12,
  color: "#666",
  margin: "2px 0",
};

const bio = {
  fontSize: 11,
  color: "#444",
  marginTop: 4,
};

const hr = {
  border: "none",
  borderTop: "1px solid #ddd",
  margin: "14px 0",
};

const titleStyle = {
  fontSize: "15px",
  fontWeight: 700,
  color: "#1f2937",
  textTransform: "uppercase",
  letterSpacing: "1px",
  borderBottom: "2px solid #1f2937",
  paddingBottom: "5px",
  marginBottom: "12px",
  marginTop: "24px",
};

const statsRow = {
  display: "grid",
  gridTemplateColumns: "repeat(3, 1fr)",
  gap: 8,
};

const box = {
  border: "1px solid #e5e5e5",
  padding: 8,
  textAlign: "center",
  borderRadius: 4,
};

const chips = {
  display: "flex",
  flexWrap: "wrap",
  gap: 6,
};

const chip = {
  fontSize: 10,
  padding: "3px 8px",
  border: "1px solid #ddd",
  borderRadius: 12,
  background: "#fafafa",
};

const card = {
  border: "1px solid #eee",
  padding: 8,
  marginBottom: 8,
};

const cardTop = {
  display: "flex",
  justifyContent: "space-between",
  fontSize: 11,
  fontWeight: "bold",
};

const desc = {
  fontSize: 10,
  color: "#555",
  marginTop: 4,
};

const footer = {
  marginTop: 12,
  textAlign: "center",
  fontSize: 9,
  color: "#999",
};

export default PortfolioPDF;
